server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/gpstracker
        username: root
        password: M.Utkarsh

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

jwt:
    secret: very_secure_secret_key_256_bits_long